### ISSUE TITLE
Range issues

### ISSUE THREAD

**Issue by PaulOckenden** [PatchworkBoy/basics-ener314rt#1]
Running on a Pi3 I'm getting awful range using this C code to drive the Pi-Mote-RT.  Just a couple of feet. I changed the SPI multiplier to account for the higher clock speed, but without success.

I found some alternative Python code (https://github.com/whaleygeek/pyenergenie) that doesn't have the same problem - the range is several rooms.

But I'm struggling to see how the code might affect the range like that. Surely that's hardware, not software?

Any ideas?

**Comment by PatchworkBoy** [comment]
This is the stock C code provided by the manufacturer via the product software link here: https://energenie4u.co.uk/catalogue/product/ENER314-RT

It just contains precompiled binaries for the first 4 addresses. Otherwise, it’s exactly as released by them. Beyond that, not a clue I’m afraid, but no such range issues here *shrug*
